#!/bin/bash

# # block npm in yarn projects and vice versa
# npm() {
#   if [ -f yarn.lock ]; then
#     echo 'use yarn';
#   else
#     command npm $*;
#   fi
# }

# yarn() {
#   if [ -f package-lock.json ]; then
#     echo 'use npm';
#   else
#     command yarn $*;
#   fi
# }

# nr() {
#   npm run "$@"
# }

# exa aliases
# alias l='exa'                                                          # ls
# alias ll='exa -lbF --git'                                                # list, size, type, git
# alias lf='exa -lbhHigUmuSa --time-style=long-iso --git --color-scale'  # all list
# alias tree='exa --tree --level=2'                                         # tree

# install tools
source tools/brew.sh
source tools/zsh.sh
source tools/utils.sh

# source ./tools/zsh.sh

# install-prerequisites() {

#   echo "Installing Rust"
#   curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
#   source $HOME/.cargo/env


#   source ~/.zshrc
# }